AnimationExtraPointers:
	dw BulbasaurAnimationExtra
	dw IvysaurAnimationExtra
	dw VenusaurAnimationExtra
	dw CharmanderAnimationExtra
	dw CharmeleonAnimationExtra
	dw CharizardAnimationExtra
	dw SquirtleAnimationExtra
	dw WartortleAnimationExtra
	dw BlastoiseAnimationExtra
	dw CaterpieAnimationExtra
	dw MetapodAnimationExtra
	dw ButterfreeAnimationExtra
	dw WeedleAnimationExtra
	dw KakunaAnimationExtra
	dw BeedrillAnimationExtra
	dw PidgeyAnimationExtra
	dw PidgeottoAnimationExtra
	dw PidgeotAnimationExtra
	dw RattataAnimationExtra
	dw RaticateAnimationExtra
	dw SpearowAnimationExtra
	dw FearowAnimationExtra
	dw EkansAnimationExtra
	dw -1 ; see ArbokAnimationExtraPointers
	dw -1 ; see PichuAnimationExtraPointers
	dw -1 ; see PikachuAnimationExtraPointers
	dw RaichuAnimationExtra
	dw SandshrewAnimationExtra
	dw SandslashAnimationExtra
	dw NidoranFAnimationExtra
	dw NidorinaAnimationExtra
	dw NidoqueenAnimationExtra
	dw NidoranMAnimationExtra
	dw NidorinoAnimationExtra
	dw NidokingAnimationExtra
	dw ClefairyAnimationExtra
	dw ClefableAnimationExtra
	dw VulpixAnimationExtra
	dw NinetalesAnimationExtra
	dw JigglypuffAnimationExtra
	dw WigglytuffAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw CrobatAnimationExtra
	dw OddishAnimationExtra
	dw GloomAnimationExtra
	dw VileplumeAnimationExtra
	dw BellossomAnimationExtra
	dw ParasAnimationExtra
	dw ParasectAnimationExtra
	dw VenonatAnimationExtra
	dw VenomothAnimationExtra
	dw DiglettAnimationExtra
	dw DugtrioAnimationExtra
	dw MeowthAnimationExtra
	dw PersianAnimationExtra
	dw PsyduckAnimationExtra
	dw GolduckAnimationExtra
	dw MankeyAnimationExtra
	dw PrimeapeAnimationExtra
	dw GrowlitheAnimationExtra
	dw ArcanineAnimationExtra
	dw PoliwagAnimationExtra
	dw PoliwhirlAnimationExtra
	dw PoliwrathAnimationExtra
	dw PolitoedAnimationExtra
	dw AbraAnimationExtra
	dw KadabraAnimationExtra
	dw AlakazamAnimationExtra
	dw MachopAnimationExtra
	dw MachokeAnimationExtra
	dw MachampAnimationExtra
	dw BellsproutAnimationExtra
	dw WeepinbellAnimationExtra
	dw VictreebelAnimationExtra
	dw TentacoolAnimationExtra
	dw TentacruelAnimationExtra
	dw GeodudeAnimationExtra
	dw GravelerAnimationExtra
	dw GolemAnimationExtra
	dw PonytaAnimationExtra
	dw RapidashAnimationExtra
	dw SlowpokeAnimationExtra
	dw SlowbroAnimationExtra
	dw SlowkingAnimationExtra
	dw MagnemiteAnimationExtra
	dw MagnetonAnimationExtra
	dw MagnezoneAnimationExtra
	dw FarfetchDAnimationExtra
	dw DoduoAnimationExtra
	dw DodrioAnimationExtra
	dw SeelAnimationExtra
	dw DewgongAnimationExtra
	dw GrimerAnimationExtra
	dw MukAnimationExtra
	dw ShellderAnimationExtra
	dw CloysterAnimationExtra
	dw GastlyAnimationExtra
	dw HaunterAnimationExtra
	dw GengarAnimationExtra
	dw OnixAnimationExtra
	dw SteelixAnimationExtra
	dw DrowzeeAnimationExtra
	dw HypnoAnimationExtra
	dw KrabbyAnimationExtra
	dw KinglerAnimationExtra
	dw VoltorbAnimationExtra
	dw ElectrodeAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorAnimationExtra
	dw CuboneAnimationExtra
	dw MarowakAnimationExtra
	dw TyrogueAnimationExtra
	dw HitmonleeAnimationExtra
	dw HitmonchanAnimationExtra
	dw HitmontopAnimationExtra
	dw LickitungAnimationExtra
	dw KoffingAnimationExtra
	dw WeezingAnimationExtra
	dw RhyhornAnimationExtra
	dw RhydonAnimationExtra
	dw RhyperiorAnimationExtra
	dw ChanseyAnimationExtra
	dw BlisseyAnimationExtra
	dw TangelaAnimationExtra
	dw TangrowthAnimationExtra
	dw KangaskhanAnimationExtra
	dw HorseaAnimationExtra
	dw SeadraAnimationExtra
	dw KingdraAnimationExtra
	dw GoldeenAnimationExtra
	dw SeakingAnimationExtra
	dw StaryuAnimationExtra
	dw StarmieAnimationExtra
	dw MrMimeAnimationExtra
	dw ScytherAnimationExtra
	dw ScizorAnimationExtra
	dw JynxAnimationExtra
	dw ElekidAnimationExtra
	dw ElectabuzzAnimationExtra
	dw ElectivireAnimationExtra
	dw MagbyAnimationExtra
	dw MagmarAnimationExtra
	dw MagmortarAnimationExtra
	dw PinsirAnimationExtra
	dw TaurosAnimationExtra
	dw MiltankAnimationExtra
	dw -1 ; see MagikarpAnimationExtraPointers
	dw -1 ; see GyaradosAnimationExtraPointers
	dw LaprasAnimationExtra
	dw DittoAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw LeafeonAnimationExtra
	dw GlaceonAnimationExtra
	dw SylveonAnimationExtra
	dw PorygonAnimationExtra
	dw Porygon2AnimationExtra
	dw PorygonZAnimationExtra
	dw OmanyteAnimationExtra
	dw OmastarAnimationExtra
	dw KabutoAnimationExtra
	dw KabutopsAnimationExtra
	dw AerodactylAnimationExtra
	dw MunchlaxAnimationExtra
	dw SnorlaxAnimationExtra
	dw ArticunoAnimationExtra
	dw ZapdosAnimationExtra
	dw MoltresAnimationExtra
	dw DratiniAnimationExtra
	dw DragonairAnimationExtra
	dw DragoniteAnimationExtra
	dw -1 ; see MewtwoAnimationExtraPointers
	dw MewAnimationExtra
	dw TogepiAnimationExtra
	dw TogeticAnimationExtra
	dw TogekissAnimationExtra

	dw ChikoritaAnimationExtra
	dw BayleefAnimationExtra
	dw MeganiumAnimationExtra
	dw CyndaquilAnimationExtra
	dw QuilavaAnimationExtra
	dw TyphlosionAnimationExtra
	dw TotodileAnimationExtra
	dw CroconawAnimationExtra
	dw FeraligatrAnimationExtra
	dw SentretAnimationExtra
	dw FurretAnimationExtra
	dw HoothootAnimationExtra
	dw NoctowlAnimationExtra
	dw SpinarakAnimationExtra
	dw AriadosAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw NatuAnimationExtra
	dw XatuAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw SudowoodoAnimationExtra
	dw SunkernAnimationExtra
	dw SunfloraAnimationExtra
	dw YanmaAnimationExtra
	dw YanmegaAnimationExtra
	dw WooperAnimationExtra
	dw QuagsireAnimationExtra
	dw MurkrowAnimationExtra
	dw HonchkrowAnimationExtra
	dw MisdreavusAnimationExtra
	dw MismagiusAnimationExtra
	dw -1 ; see UnownAnimationExtraPointers
	dw WobbuffetAnimationExtra
	dw GirafarigAnimationExtra
	dw PinecoAnimationExtra
	dw ForretressAnimationExtra
	dw DunsparceAnimationExtra
	dw GligarAnimationExtra
	dw GliscorAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw QwilfishAnimationExtra
	dw ShuckleAnimationExtra
	dw HeracrossAnimationExtra
	dw SneaselAnimationExtra
	dw WeavileAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw SlugmaAnimationExtra
	dw MagcargoAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw MamoswineAnimationExtra
	dw CorsolaAnimationExtra
	dw RemoraidAnimationExtra
	dw OctilleryAnimationExtra
	dw SkarmoryAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw PhanpyAnimationExtra
	dw DonphanAnimationExtra
	dw SmeargleAnimationExtra
	dw RaikouAnimationExtra
	dw EnteiAnimationExtra
	dw SuicuneAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw LugiaAnimationExtra
	dw HoOhAnimationExtra
	dw CelebiAnimationExtra
	dw EggAnimationExtra
