FramesPointers:
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw CaterpieFrames
	dw MetapodFrames
	dw ButterfreeFrames
	dw WeedleFrames
	dw KakunaFrames
	dw BeedrillFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw RattataFrames
	dw RaticateFrames
	dw SpearowFrames
	dw FearowFrames
	dw EkansFrames
	dw -1 ; see ArbokFramesPointers
	dw -1 ; see PichuFramesPointers
	dw -1 ; see PikachuFramesPointers
	dw RaichuFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw CleffaFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw IgglybuffFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ZubatFrames
	dw GolbatFrames
	dw CrobatFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw BellossomFrames
	dw ParasFrames
	dw ParasectFrames
	dw VenonatFrames
	dw VenomothFrames
	dw DiglettFrames
	dw DugtrioFrames
	dw MeowthFrames
	dw PersianFrames
	dw PsyduckFrames
	dw GolduckFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw PolitoedFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw SlowkingFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw FarfetchDFrames
	dw DoduoFrames
	dw DodrioFrames
	dw SeelFrames
	dw DewgongFrames
	dw GrimerFrames
	dw MukFrames
	dw ShellderFrames
	dw CloysterFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw SteelixFrames
	dw DrowzeeFrames
	dw HypnoFrames
	dw KrabbyFrames
	dw KinglerFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw CuboneFrames
	dw MarowakFrames
	dw TyrogueFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw HitmontopFrames
	dw LickitungFrames
	dw LickilickyFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw RhyperiorFrames
	dw ChanseyFrames
	dw BlisseyFrames
	dw TangelaFrames
	dw TangrowthFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw KingdraFrames
	dw GoldeenFrames
	dw SeakingFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimeFrames
	dw ScytherFrames
	dw ScizorFrames
	dw JynxFrames
	dw ElekidFrames
	dw ElectabuzzFrames
	dw ElectivireFrames
	dw MagbyFrames
	dw MagmarFrames
	dw MagmortarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw MiltankFrames
	dw -1 ; see MagikarpFramesPointers
	dw -1 ; see GyaradosFramesPointers
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw SylveonFrames
	dw PorygonFrames
	dw Porygon2Frames
	dw PorygonZFrames
	dw OmanyteFrames
	dw OmastarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw MunchlaxFrames
	dw SnorlaxFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw -1 ; see MewtwoFramesPointers
	dw MewFrames
	dw TogepiFrames
	dw TogeticFrames
	dw TogekissFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
	dw EggFrames
